### ISSUE TITLE
xml/find 404

### ISSUE THREAD

**Issue by luzik** [richardasaurus/imdb-pie#47]
imdb.search_for_title("The Dark Knight")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/luzik/.local/lib/python3.5/site-packages/imdbpie/imdbpie.py", line 148, in search_for_title
    'http://www.imdb.com/xml/find?{0}'.format(query_params)
  File "/home/luzik/.local/lib/python3.5/site-packages/imdbpie/imdbpie.py", line 286, in _get
    resp.raise_for_status()
  File "/home/luzik/.local/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://www.imdb.com/xml/find?tt=on&q=The+Dark+Knight&json=1&nr=1

**Comment by duramato** [comment]
That was fixed on version 4.4.1

**Comment by duramato** [comment]
That was fixed on version 4.4.1

**Comment by luzik** [comment]
Uh ..sorry
