### ISSUE TITLE
Unable to run on multiple versions of python on same system

### ISSUE THREAD

**Issue by labrys** [richardasaurus/imdb-pie#74]
Using `imdbpie` with Py3 prior to Py2 causes `imdbpie` to fail on Py2 with `ValueError: unsupported pickle protocol: 4` due to different Pickle protocols.

To reproduce delete any existing cache, run `imdbpie` with python 3 then run with python 2.

Example error run Win 10:
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Python\Python-2.7.14-x86\lib\site-packages\imdbpie\imdbpie.py", line 167, in get_popular_shows
    return self._get_resource('/chart/tvmeter')
  File "C:\Python\Python-2.7.14-x86\lib\site-packages\imdbpie\imdbpie.py", line 268, in _get_resource
    return self._get(url=url)['resource']
  File "C:\Python\Python-2.7.14-x86\lib\site-packages\imdbpie\imdbpie.py", line 275, in _get
    headers.update(self.get_auth_headers(path))
  File "C:\Python\Python-2.7.14-x86\lib\site-packages\imdbpie\auth.py", line 113, in get_auth_headers
    creds, soon_expires = self._creds_soon_expiring()
  File "C:\Python\Python-2.7.14-x86\lib\site-packages\imdbpie\auth.py", line 98, in _creds_soon_expiring
    creds = self._get_creds()
  File "C:\Python\Python-2.7.14-x86\lib\site-packages\imdbpie\auth.py", line 86, in _get_creds
    return cache.get(self._CREDS_STORAGE_KEY)
  File "C:\Python\Python-2.7.14-x86\lib\site-packages\diskcache\core.py", line 907, in get
    value = self._disk.fetch(mode, filename, db_value, read)
  File "C:\Python\Python-2.7.14-x86\lib\site-packages\diskcache\core.py", line 279, in fetch
    return pickle.load(BytesIO(value))
ValueError: unsupported pickle protocol: 4
```

**Comment by VeNoMouS** [comment]
@labrys want to cherry pick 4f46bc3e7c6c00055c3f978258750a6f80c8a5ab and confirm that's ok? i tested it my end && it seemed to work fine.

**Comment by VeNoMouS** [comment]
ah , just realised your on wintendo, not sure where the temp dir is on that, maybe `c:\temp`?

**Comment by labrys** [comment]
I won't be able to check it until this weekend.
The cache on windows is located at `C:\Users\USERNAME\AppData\Local\Temp\cache.db`
